# Generated by Django 2.2.17 on 2021-03-18 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_authgit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 11, 21, 51, 13720, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
