# Generated by Django 2.2.17 on 2021-03-20 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_auto_20210318_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 11, 27, 47, 234361, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
