# Generated by Django 2.2.17 on 2021-03-28 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0009_auto_20210324_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 13, 43, 28, 367074, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
